name: CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1

    - name: Setup .NET 7
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x

    - name: Install iOS workload
      run: dotnet workload install maui ios maccatalyst
      
    - name: Restore dotnet tools
      run: dotnet tool restore

    - name: Run the Cake script
      run: dotnet cake

    - uses: actions/upload-artifact@master
      with:
        name: NugetPackage
        path: artifacts
